name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-nns-cli:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: ['1.62.1']
        os: [ubuntu-20.04, macos-11]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-1

      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}

      - name: Build
        shell: bash
        run: |
          cargo build --release
        env:
          RUST_BACKTRACE: 1

      - name: 'Upload nns-cli module'
        uses: actions/upload-artifact@v2
        with:
          name: nns-cli-${{ runner.os }}
          path: ./target/release/nns-cli
